"""Render clockwork manifests into scheduler artifacts."""

from __future__ import annotations

from pathlib import Path

from .model import JobSpec, Manifest


def _format_bool(value: bool) -> str:
    return "true" if value else "false"


def _quote_systemd_environment(key: str, value: str) -> str:
    payload = f"{key}={value}".replace("\\", "\\\\").replace('"', '\\"')
    return f'Environment="{payload}"'


def render_service_unit(job: JobSpec) -> str:
    lines = ["[Unit]", f"Description={job.description}"]
    if job.after:
        lines.append(f"After={' '.join(job.after)}")
    if job.wants:
        lines.append(f"Wants={' '.join(job.wants)}")
    if job.start_limit_interval_sec:
        lines.append(f"StartLimitIntervalSec={job.start_limit_interval_sec}")

    lines.extend(["", "[Service]", f"Type={job.service_type}"])
    if job.user:
        lines.append(f"User={job.user}")
    if job.group:
        lines.append(f"Group={job.group}")
    if job.working_directory:
        lines.append(f"WorkingDirectory={job.working_directory}")
    for environment_file in job.environment_files:
        lines.append(f"EnvironmentFile={environment_file}")
    for key in sorted(job.environment):
        lines.append(_quote_systemd_environment(key, job.environment[key]))
    lines.append(f"ExecStart={job.exec_start}")
    if job.restart:
        lines.append(f"Restart={job.restart}")
    if job.restart_sec:
        lines.append(f"RestartSec={job.restart_sec}")
    if job.standard_output:
        lines.append(f"StandardOutput={job.standard_output}")
    if job.standard_error:
        lines.append(f"StandardError={job.standard_error}")

    if job.service_install_wanted_by:
        lines.extend(["", "[Install]"])
        for target in job.service_install_wanted_by:
            lines.append(f"WantedBy={target}")
    return "\n".join(lines) + "\n"


def render_timer_unit(job: JobSpec) -> str:
    if job.timer is None:
        raise ValueError(f"job {job.name!r} does not define a timer")

    description = job.timer_description or f"Run {job.description} on schedule"
    unit_name = job.timer.unit or job.service_unit_name()

    lines = ["[Unit]", f"Description={description}", "", "[Timer]"]
    if job.timer.kind == "calendar":
        lines.append(f"OnCalendar={job.timer.on_calendar}")
    else:
        if job.timer.on_boot_sec:
            lines.append(f"OnBootSec={job.timer.on_boot_sec}")
        if job.timer.on_unit_active_sec:
            lines.append(f"OnUnitActiveSec={job.timer.on_unit_active_sec}")
    lines.append(f"Persistent={_format_bool(job.timer.persistent)}")
    lines.append(f"Unit={unit_name}")
    if job.timer.accuracy_sec:
        lines.append(f"AccuracySec={job.timer.accuracy_sec}")
    if job.timer.randomized_delay_sec:
        lines.append(f"RandomizedDelaySec={job.timer.randomized_delay_sec}")
    lines.extend(["", "[Install]", f"WantedBy={job.timer.install_wanted_by}"])
    return "\n".join(lines) + "\n"


def render_crontab(manifest: Manifest) -> str:
    lines = [
        f"# Generated by clockwork from {manifest.path}",
        "# Review paths and commands before installing with crontab.",
    ]
    for job in manifest.jobs:
        if job.cron is None:
            continue
        lines.extend(["", f"# {job.description}"])
        for comment in job.cron.comments:
            lines.append(f"# {comment}")
        if job.cron.timezone:
            lines.append(f"CRON_TZ={job.cron.timezone}")
        lines.append(f"{job.cron.expression} {job.cron.command}")
    return "\n".join(lines) + "\n"


def render_target(manifest: Manifest, target: str) -> dict[str, str]:
    if target not in {"systemd-user", "systemd-system", "cron"}:
        raise ValueError(f"Unsupported render target: {target!r}")
    if target == "cron":
        return {f"{Path(manifest.path).stem}.crontab": render_crontab(manifest)}

    expected_scope = "user" if target == "systemd-user" else "system"
    rendered: dict[str, str] = {}
    for job in manifest.jobs:
        if job.scope != expected_scope:
            continue
        rendered[job.service_unit_name()] = render_service_unit(job)
        if job.timer is not None:
            rendered[job.timer_unit_name()] = render_timer_unit(job)
    return rendered


def write_rendered_files(output_dir: str | Path, files: dict[str, str]) -> list[Path]:
    output_path = Path(output_dir)
    try:
        output_path.mkdir(parents=True, exist_ok=True)
    except PermissionError:
        raise PermissionError(
            f"cannot write to {output_path} — run with sudo for system-scope jobs"
        ) from None
    written: list[Path] = []
    for name, content in files.items():
        target = output_path / name
        try:
            target.write_text(content, encoding="utf-8")
        except PermissionError:
            raise PermissionError(
                f"cannot write {target} — run with sudo for system-scope jobs"
            ) from None
        written.append(target)
    return written
