#!/usr/bin/env bash
# Generate CA, server, and client certificates for clockwork-web mTLS,
# create an iOS/macOS mobile profile, and register certs with Firefox and Chromium.
#
# Usage:
#   CLOCKWORK_WG_IP=<wireguard-ip> bash scripts/setup-mtls.sh
#   CLOCKWORK_WG_IP=10.8.0.1 CLOCKWORK_CERT_DIR=~/.config/clockwork/certs bash scripts/setup-mtls.sh
set -euo pipefail

CERT_DIR="${CLOCKWORK_CERT_DIR:-$HOME/.config/clockwork/certs}"
WG_IP="${CLOCKWORK_WG_IP:-10.0.0.1}"
HOSTNAME="${CLOCKWORK_HOSTNAME:-config.clockwork.internal}"
# Optional: include a second hostname in the server cert SAN.
# Set to files.snowbridge.internal when running the combined Caddy setup
# (scripts/setup_caddy.py) so both sites share the same server TLS cert.
EXTRA_HOSTNAME="${CLOCKWORK_EXTRA_HOSTNAME:-}"
DAYS_CA=3650
DAYS_LEAF=825  # ~2 years, max trusted by modern browsers

mkdir -p "$CERT_DIR"
chmod 700 "$CERT_DIR"

# ── 1. CA ──────────────────────────────────────────────────────────────────
echo "==> Generating CA (valid ${DAYS_CA} days)..."
openssl genrsa -out "$CERT_DIR/ca.key" 4096
openssl req -new -x509 -days "$DAYS_CA" \
  -key "$CERT_DIR/ca.key" \
  -out "$CERT_DIR/ca.crt" \
  -subj "/CN=Clockwork CA/O=Portfolio/OU=Scheduler"

# ── 2. Server cert (with SAN for the WireGuard IP) ─────────────────────────
echo "==> Generating server certificate for $HOSTNAME / $WG_IP (valid ${DAYS_LEAF} days)..."
openssl genrsa -out "$CERT_DIR/server.key" 2048
openssl req -new \
  -key "$CERT_DIR/server.key" \
  -out "$CERT_DIR/server.csr" \
  -subj "/CN=$HOSTNAME/O=Clockwork/OU=Server"
# SAN covers both the DNS hostname and the raw WireGuard IP so curl/Caddy/browsers all accept it.
# CLOCKWORK_EXTRA_HOSTNAME (e.g. files.snowbridge.internal) adds a second DNS SAN so a single
# cert can serve the combined Caddy config generated by scripts/setup_caddy.py.
SAN_VALUE="subjectAltName=DNS:${HOSTNAME},IP:${WG_IP}"
if [ -n "$EXTRA_HOSTNAME" ]; then
  SAN_VALUE="${SAN_VALUE},DNS:${EXTRA_HOSTNAME}"
  echo "  Extra SAN hostname: $EXTRA_HOSTNAME"
fi
openssl x509 -req -days "$DAYS_LEAF" \
  -in "$CERT_DIR/server.csr" \
  -CA "$CERT_DIR/ca.crt" -CAkey "$CERT_DIR/ca.key" -CAcreateserial \
  -extfile <(printf "%s" "$SAN_VALUE") \
  -out "$CERT_DIR/server.crt"

# ── 3. Client cert ─────────────────────────────────────────────────────────
echo "==> Generating client certificate (valid ${DAYS_LEAF} days)..."
openssl genrsa -out "$CERT_DIR/client.key" 2048
openssl req -new \
  -key "$CERT_DIR/client.key" \
  -out "$CERT_DIR/client.csr" \
  -subj "/CN=clockwork-client/O=Portfolio/OU=Admin"
# Add clientAuth EKU so iOS/browsers accept it as a client identity
openssl x509 -req -days "$DAYS_LEAF" \
  -in "$CERT_DIR/client.csr" \
  -CA "$CERT_DIR/ca.crt" -CAkey "$CERT_DIR/ca.key" -CAcreateserial \
  -extfile <(printf "basicConstraints=critical,CA:FALSE\nkeyUsage=critical,digitalSignature,keyEncipherment\nextendedKeyUsage=clientAuth\nsubjectKeyIdentifier=hash\nauthorityKeyIdentifier=keyid,issuer\n") \
  -out "$CERT_DIR/client.crt"

# ── 4. PKCS12 bundle (passphrase-protected) ────────────────────────────────
echo "==> Bundling client cert as PKCS12..."
P12_PASS_FILE="$CERT_DIR/client.p12.passphrase"
# Generate a new passphrase only if one does not already exist (so re-runs
# that regenerate the p12 preserve the same passphrase).
if [ ! -f "$P12_PASS_FILE" ]; then
  openssl rand -base64 24 > "$P12_PASS_FILE"
  chmod 600 "$P12_PASS_FILE"
fi
P12_PASS="$(cat "$P12_PASS_FILE")"
openssl pkcs12 -export \
  -out "$CERT_DIR/client.p12" \
  -inkey "$CERT_DIR/client.key" \
  -in "$CERT_DIR/client.crt" \
  -certfile "$CERT_DIR/ca.crt" \
  -passout pass:"$P12_PASS"

chmod 600 "$CERT_DIR"/*.key "$CERT_DIR"/*.p12

# ── 5. Mobile profile (.mobileconfig for iOS / macOS) ─────────────────────
echo "==> Generating mobile profile (.mobileconfig)..."
python3 - "$CERT_DIR" "$WG_IP" <<'PYEOF'
import hashlib, plistlib, ssl, sys, uuid
from pathlib import Path

cert_dir = Path(sys.argv[1])
wg_ip = sys.argv[2]

def load_der(path):
    raw = path.read_bytes()
    if b"-----BEGIN CERTIFICATE-----" in raw:
        return ssl.PEM_cert_to_DER_cert(raw.decode("ascii"))
    return raw

def stable_uuid(label, digest):
    return str(uuid.uuid5(uuid.NAMESPACE_DNS, f"{label}:{digest}")).upper()

ca_der   = load_der(cert_dir / "ca.crt")
p12_data = (cert_dir / "client.p12").read_bytes()
digest   = hashlib.sha256(ca_der + p12_data).hexdigest()

profile = {
    "PayloadType": "Configuration",
    "PayloadVersion": 1,
    "PayloadIdentifier": "local.clockwork.web-mtls",
    "PayloadUUID": stable_uuid("clockwork-mtls-profile", digest),
    "PayloadDisplayName": f"Clockwork Web mTLS ({wg_ip})",
    "PayloadDescription": (
        "Trust profile and client identity for Clockwork web UI "
        "private mTLS access over WireGuard."
    ),
    "PayloadOrganization": "clockwork",
    "PayloadRemovalDisallowed": False,
    "PayloadContent": [
        {
            "PayloadType": "com.apple.security.root",
            "PayloadVersion": 1,
            "PayloadIdentifier": "local.clockwork.web-mtls.root",
            "PayloadUUID": stable_uuid("clockwork-mtls-root", digest),
            "PayloadDisplayName": "Clockwork CA",
            "PayloadDescription": (
                "Installs the Clockwork CA so the device trusts "
                "the private HTTPS endpoint."
            ),
            "PayloadCertificateFileName": "ca.crt",
            "PayloadContent": ca_der,
        },
        {
            "PayloadType": "com.apple.security.pkcs12",
            "PayloadVersion": 1,
            "PayloadIdentifier": "local.clockwork.web-mtls.identity",
            "PayloadUUID": stable_uuid("clockwork-mtls-identity", digest),
            "PayloadDisplayName": "Clockwork mTLS Client Identity",
            "PayloadDescription": (
                "Installs the client certificate required for "
                "Clockwork private mTLS access."
            ),
            "PayloadCertificateFileName": "client.p12",
            "PayloadContent": p12_data,
        },
    ],
}

out = cert_dir / "clockwork-web.mobileconfig"
out.write_bytes(plistlib.dumps(profile, fmt=plistlib.FMT_XML, sort_keys=False))
out.chmod(0o644)
print(f"  Mobile profile:  {out}")
PYEOF

# ── 6. Firefox NSS databases ───────────────────────────────────────────────
echo "==> Adding certs to Firefox NSS databases..."
if command -v certutil >/dev/null 2>&1; then
  found_ff=0
  for profile_dir in \
      "$HOME"/.mozilla/firefox/*.default \
      "$HOME"/.mozilla/firefox/*.default-release \
      "$HOME"/.mozilla/firefox/*.default-esr \
      "$HOME"/.var/app/org.mozilla.firefox/.mozilla/firefox/*.default-release; do
    [ -d "$profile_dir" ] || continue
    found_ff=1
    db="sql:$profile_dir"
    # Remove stale entries first (handles repeated runs accumulating duplicates)
    for nick in "Clockwork CA" "clockwork-client - Portfolio" "clockwork-client"; do
      for i in $(seq 1 10); do certutil -D -d "$db" -n "$nick" 2>/dev/null || break; done
    done
    # CA → trust as root for TLS server auth
    if certutil -A -d "$db" -n "Clockwork CA" -t "CT,," \
         -i "$CERT_DIR/ca.crt" 2>/dev/null; then
      echo "  [FF] CA added:     $(basename "$profile_dir")"
    else
      echo "  [FF] CA add failed: $(basename "$profile_dir")"
    fi
    # Client identity
    if pk12util -i "$CERT_DIR/client.p12" -d "$db" -W "$P12_PASS" 2>/dev/null; then
      echo "  [FF] Client cert added: $(basename "$profile_dir")"
    else
      echo "  [FF] Client cert add failed: $(basename "$profile_dir")"
    fi
  done
  [ "$found_ff" -eq 0 ] && echo "  No Firefox profiles found."
else
  echo "  certutil not found — install nss-tools (dnf install nss-tools  /  apt install libnss3-tools)"
fi

# ── 7. Chromium / Chrome NSS database (~/.pki/nssdb) ──────────────────────
echo "==> Adding certs to Chromium NSS database..."
if command -v certutil >/dev/null 2>&1; then
  CHROMIUM_DB="$HOME/.pki/nssdb"
  if [ ! -d "$CHROMIUM_DB" ]; then
    echo "  Creating Chromium NSS database at $CHROMIUM_DB..."
    mkdir -p "$CHROMIUM_DB"
    certutil -d "sql:$CHROMIUM_DB" -N --empty-password
  fi
  for nick in "Clockwork CA" "clockwork-client - Portfolio" "clockwork-client"; do
    for i in $(seq 1 10); do certutil -D -d "sql:$CHROMIUM_DB" -n "$nick" 2>/dev/null || break; done
  done
  if certutil -A -d "sql:$CHROMIUM_DB" -n "Clockwork CA" -t "CT,," \
       -i "$CERT_DIR/ca.crt" 2>/dev/null; then
    echo "  [Chromium] CA added."
  else
    echo "  [Chromium] CA add failed."
  fi
  if pk12util -i "$CERT_DIR/client.p12" -d "sql:$CHROMIUM_DB" -W "$P12_PASS" 2>/dev/null; then
    echo "  [Chromium] Client cert added."
  else
    echo "  [Chromium] Client cert add failed."
  fi
else
  echo "  certutil not found — skipping Chromium."
fi

# ── 8. Local /etc/hosts entry (so the hostname resolves on this machine) ──
echo "==> Checking local /etc/hosts for $HOSTNAME..."
if getent hosts "$HOSTNAME" >/dev/null 2>&1; then
  echo "  Already resolves: $(getent hosts "$HOSTNAME")"
else
  if printf '127.0.0.1 %s\n' "$HOSTNAME" | sudo tee -a /etc/hosts >/dev/null 2>&1; then
    echo "  Added: 127.0.0.1 $HOSTNAME"
  else
    echo "  Could not write /etc/hosts. Add manually:"
    echo "    echo '127.0.0.1 $HOSTNAME' | sudo tee -a /etc/hosts"
  fi
fi

# ── 9. dnsmasq config for the local WireGuard server ───────────────────────
DNSMASQ_SNIPPET="${CERT_DIR%/certs}/dnsmasq-clockwork.conf"
DNSMASQ_DEST="/etc/dnsmasq.d/clockwork.conf"
cat > "$DNSMASQ_SNIPPET" <<DNSCONF
# Tells dnsmasq to resolve $HOSTNAME to the WireGuard server IP
# so all VPN peers can reach the clockwork web UI.
# Generated by scripts/setup-mtls.sh — re-run to update.

address=/$HOSTNAME/$WG_IP
DNSCONF
echo "  dnsmasq snippet: $DNSMASQ_SNIPPET"

# Auto-install if dnsmasq.d exists (this machine is the WireGuard/dnsmasq server)
if [ -d /etc/dnsmasq.d ]; then
  if [ -w /etc/dnsmasq.d ]; then
    cp "$DNSMASQ_SNIPPET" "$DNSMASQ_DEST"
    echo "  Installed: $DNSMASQ_DEST"
    if systemctl is-active --quiet dnsmasq 2>/dev/null; then
      systemctl restart dnsmasq
      echo "  Restarted dnsmasq."
    else
      echo "  dnsmasq not running — start it with: sudo systemctl enable --now dnsmasq"
    fi
  else
    echo "  /etc/dnsmasq.d not writable. Install manually:"
    echo "    sudo cp $DNSMASQ_SNIPPET $DNSMASQ_DEST"
    echo "    sudo systemctl restart dnsmasq"
  fi
else
  echo "  /etc/dnsmasq.d not found — dnsmasq may not be installed on this host."
  echo "  If dnsmasq runs elsewhere, copy $DNSMASQ_SNIPPET there as $DNSMASQ_DEST"
fi

# ── Summary ────────────────────────────────────────────────────────────────
echo ""
echo "Certificates written to: $CERT_DIR"
echo ""
echo "  CA cert:        $CERT_DIR/ca.crt"
echo "  Server cert:    $CERT_DIR/server.crt"
echo "  Server key:     $CERT_DIR/server.key"
echo "  Client cert:    $CERT_DIR/client.crt"
echo "  Client p12:     $CERT_DIR/client.p12    ← import into desktop browsers manually if needed"
echo "  P12 passphrase: $P12_PASS  (also saved to $P12_PASS_FILE)"
echo "  Mobile profile: $CERT_DIR/clockwork-web.mobileconfig  ← send to iOS/macOS device"
echo ""
echo "iOS install steps:"
echo "  1. AirDrop or share clockwork-web.mobileconfig to the device."
echo "  2. Tap the file → Settings → Profile Downloaded → Install."
echo "  3. When prompted for the certificate passphrase, enter: $P12_PASS"
echo "  4. Settings → General → About → Certificate Trust Settings → enable Clockwork CA."
echo ""
echo "Caddy config:   config/web/caddy/Caddyfile.local  (clockwork-only)"
echo "  Flask runs on 127.0.0.1:5000 — Caddy terminates mTLS on the WireGuard interface."
echo "  sudo caddy run --config config/web/caddy/Caddyfile.local"
echo ""
echo "Combined Caddy (clockwork + snowbridge filebrowser on one Caddy instance):"
echo "  Re-run with CLOCKWORK_EXTRA_HOSTNAME=files.snowbridge.internal to add snowbridge SAN,"
echo "  then generate the combined Caddyfile:"
echo "    CLOCKWORK_WG_IP=$WG_IP CLOCKWORK_EXTRA_HOSTNAME=files.snowbridge.internal \\"
echo "        bash scripts/setup-mtls.sh"
echo "    python3 scripts/setup_caddy.py"
echo ""
echo "dnsmasq: $DNSMASQ_DEST"
echo "  Resolves $HOSTNAME → $WG_IP for all WireGuard peers."
echo "  Re-run this script any time the WireGuard IP changes."
echo ""
echo "Install and start the Flask service (Caddy handles TLS — no SSL env vars needed):"
echo "  clockwork install --manifest examples/clockwork/clockwork-web.toml --target systemd-user"
echo "  systemctl --user daemon-reload"
echo "  systemctl --user enable --now clockwork-web.service"
echo ""
echo "Access at: https://$HOSTNAME"

# ── 10. Stage per-device mobileconfig to snowbridge share ─────────────────────
EXPORT_SCRIPT="$(dirname "$0")/export_clockwork_mtls_profile.py"
if [ -f "$EXPORT_SCRIPT" ]; then
  echo ""
  echo "==> Staging default mobileconfig to /srv/snowbridge/share/tmp/..."
  if sudo python3 "$EXPORT_SCRIPT" --device-name iphone \
      --ca-cert "$CERT_DIR/ca.crt" \
      --ca-key "$CERT_DIR/ca.key" \
      --issued-dir "$CERT_DIR/issued"; then
    echo "  Done. Use --device-name <name> to issue additional per-device profiles:"
    echo "    sudo python3 $EXPORT_SCRIPT --device-name <name>"
    echo "    sudo python3 $EXPORT_SCRIPT --device-name <name> --rotate  # regenerate cert"
  else
    echo "  Staging failed — run manually:"
    echo "    sudo python3 $EXPORT_SCRIPT --device-name iphone"
  fi
else
  echo ""
  echo "  Export script not found: $EXPORT_SCRIPT"
fi
